### PR TITLE
[RC] Add more information to Fast Recovery

### PR DESCRIPTION
**Pull request by gazev**
I tried to clarify the explanation because I think the phrasing was a bit misleading. I think it would be ideal to showcase the TCP State Machine found in the classes slides, as it is explains the states more clearly than any text ever could

### CODE REVIEW

**Comment by gazev** [comment]
I am not 100% sure on the part where it says "sending only the lost packets" but I think the important part to emphasize was that fast recovery is a state that precedes congestion avoidance and that differs from the other states when dealing with duplicate packets

**Comment by diogotcorreia** [comment]
If you want to, you can recreate the image from the slides using draw.io and then add the SVG here

**Comment by gazev** [comment]
Untitled Diagram drawio


> If you want to, you can recreate the image from the slides using draw.io and then add the SVG here
Is this it? 👀

**Comment by gazev** [comment]
Where should this be added?

**Comment by diogotcorreia** [comment]
I meant recreating the diagram, not importing a screenshot of it :sweat_smile: 
The point here is to have our own images due to copyright issues (it could be a simplified version of the one in the slides, if you feel that one has too much information)

**Comment by gazev** [comment]
> I meant recreating the diagram, not importing a screenshot of it 😅 The point here is to have our own images due to copyright issues (it could be a simplified version of the one in the slides, if you feel that one has too much information)

My bad 😅😅😅 

I can do it when I get some time, but I think it will be hard before the exam. So I think it's okay to simply push the clarification and a mention to look at the STM. I think it's important because the exam is nearing 👀

**Comment by diogotcorreia** [comment]
Sure, it was just a suggestion since you mentioned in the PR description.
I'll take a look at the content and review it in a second.

Could you just run prettier (`yarn format`) to pass the CI?

**Comment by gazev** [comment]
> Sure, it was just a suggestion since you mentioned in the PR description. I'll take a look at the content and review it in a second.
> 
> Could you just run prettier (`yarn format`) to pass the CI?

I don't have yarn setup (I am editing it on vim :l ), but if you give me some time I will do that and also add a mention to STM to the PR

**Comment by gazev** [comment]
I think it's ready 👍

**Review by diogotcorreia — APPROVED** [review]

**Pull request merged**
